'use client'
/* eslint-disable @typescript-eslint/no-explicit-any -- compact view model is returned by a migration-backed action. */

import { useMemo, useState, useTransition } from 'react'
import { useRouter } from 'next/navigation'
import { toast } from 'sonner'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { cancelMetalScrapSale, reviewMetalScrapLot, sellMetalScrap } from '@/lib/actions/future-inventory'
import { ROUTES } from '@/lib/constants/routes'

export function MetalScrapPage({ data }: { data: any }) {
  const router = useRouter(); const [pending, startTransition] = useTransition(); const [weights, setWeights] = useState<Record<string,string>>({}); const [reviewReasons,setReviewReasons]=useState<Record<string,string>>({}); const [amount, setAmount] = useState(''); const [date, setDate] = useState(new Date().toISOString().slice(0,10)); const [buyer,setBuyer]=useState(''); const [document,setDocument]=useState(''); const [comment,setComment]=useState('')
  const selected = useMemo(() => data.lots.map((lot: any) => ({ lotId: lot.id, weightKg: Number(weights[lot.id] || 0) })).filter((item: any) => item.weightKg > 0), [data.lots, weights]); const totalWeight = selected.reduce((sum: number,item: any)=>sum+item.weightKg,0)
  function href(factory=data.selectedFactory,status=data.status){return `${ROUTES.INVENTORY_METAL_SCRAP}?factory=${factory}&status=${status}`}
  function sell(){startTransition(async()=>{const result=await sellMetalScrap({factoryId:data.selectedFactory,saleDate:date,amountUah:Number(amount),buyer,document,comment,items:selected});if(!result.success){toast.error(result.error);return}toast.success('Сдача проведена, финансовый приход создан');setWeights({});setAmount('');router.refresh()})}
  function cancel(id:string){const reason=window.prompt('Укажите обязательную причину отмены сдачи');if(!reason)return;startTransition(async()=>{const result=await cancelMetalScrapSale(id,reason);if(!result.success){toast.error(result.error);return}toast.success('Сдача отменена, вес возвращён');router.refresh()})}
  function review(lot:any){const actual=Number(weights[lot.id] ?? lot.expected_weight_kg);startTransition(async()=>{const result=await reviewMetalScrapLot(lot.id,actual,reviewReasons[lot.id]);if(!result.success){toast.error(result.error);return}toast.success('Остаток перепроверен и разблокирован');router.refresh()})}
  return <main className="space-y-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-2xl font-semibold">Металлолом</h1><p className="text-muted-foreground">Остатки разделены по заводу, материалу и источнику.</p></div><div><Label>Завод</Label><Select value={data.selectedFactory} onValueChange={(value)=>router.push(href(value))}><SelectTrigger className="w-56"><SelectValue>{data.factories.find((f:any)=>f.id===data.selectedFactory)?.name || 'Выберите завод'}</SelectValue></SelectTrigger><SelectContent>{data.factories.map((f:any)=><SelectItem key={f.id} value={f.id}>{f.name}</SelectItem>)}</SelectContent></Select></div></div>
    <div className="grid gap-3 sm:grid-cols-4">{[['Будущий',data.aggregates.future],['Доступно',data.aggregates.available],['Заблокировано',data.aggregates.blocked],['Сдано',data.aggregates.sold]].map(([label,value])=><Card key={String(label)}><CardContent className="pt-5"><p className="text-sm text-muted-foreground">{label}</p><p className="font-mono text-2xl font-semibold">{Number(value).toFixed(3)} кг</p></CardContent></Card>)}</div>
    <Tabs value={data.status} onValueChange={(value)=>router.push(href(data.selectedFactory,value))}><TabsList><TabsTrigger value="future">Будущий</TabsTrigger><TabsTrigger value="available">Фактический</TabsTrigger><TabsTrigger value="review_required">Перепроверить</TabsTrigger></TabsList></Tabs>
    <Card><CardHeader><CardTitle>Партии</CardTitle></CardHeader><CardContent className="space-y-2">{data.lots.map((lot:any)=><div key={lot.id} className="grid gap-3 rounded-lg border p-3 md:grid-cols-[1fr_150px_minmax(150px,1fr)] md:items-end"><div><p className="font-medium">{lot.material_name}{lot.material_grade?` · ${lot.material_grade}`:''}</p><p className="text-sm text-muted-foreground">{lot.source_type==='inventory_conversion'?`Переведено со склада · строка ${lot.source_inventory_id?.slice(0,8)}`:`${lot.machines?.name || 'Машина'} · заявка ${lot.request_id?.slice(0,8)}`} · доступно {Number(lot.available_weight_kg).toFixed(3)} кг</p></div>{data.status==='available'&&data.canManageSales&&<><div><Label htmlFor={`weight-${lot.id}`}>Сдать, кг</Label><Input id={`weight-${lot.id}`} type="number" min="0" max={lot.available_weight_kg} step="0.001" value={weights[lot.id]||''} onChange={(e)=>setWeights({...weights,[lot.id]:e.target.value})}/></div><p className="font-mono text-sm">Сдано: {Number(lot.sold_weight_kg).toFixed(3)} кг</p></>}{data.status==='review_required'&&data.canManageScrap&&<><div><Label htmlFor={`review-weight-${lot.id}`}>Фактический вес, кг</Label><Input id={`review-weight-${lot.id}`} type="number" min={lot.sold_weight_kg} step="0.001" value={weights[lot.id]??lot.expected_weight_kg} onChange={(e)=>setWeights({...weights,[lot.id]:e.target.value})}/></div><div><Label htmlFor={`review-reason-${lot.id}`}>Причина при изменении</Label><div className="flex gap-2"><Input id={`review-reason-${lot.id}`} value={reviewReasons[lot.id]||''} onChange={(e)=>setReviewReasons({...reviewReasons,[lot.id]:e.target.value})}/><Button disabled={pending} onClick={()=>review(lot)}>Подтвердить</Button></div></div></>}</div>)}{data.lots.length===0&&<p className="py-8 text-center text-muted-foreground">В этой категории партий нет.</p>}</CardContent></Card>
    {data.status==='available'&&data.canManageSales&&<Card><CardHeader><CardTitle>Сдать выбранный металлолом</CardTitle></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div><Label>Дата *</Label><Input type="date" value={date} onChange={(e)=>setDate(e.target.value)}/></div><div><Label>Общая сумма, UAH *</Label><Input type="number" min="0" step="0.01" value={amount} onChange={(e)=>setAmount(e.target.value)}/></div><div><Label>Покупатель</Label><Input value={buyer} onChange={(e)=>setBuyer(e.target.value)}/></div><div><Label>Документ</Label><Input value={document} onChange={(e)=>setDocument(e.target.value)}/></div><div className="sm:col-span-2 lg:col-span-3"><Label>Комментарий</Label><Input value={comment} onChange={(e)=>setComment(e.target.value)}/></div><div className="flex items-end"><Button className="w-full" disabled={pending||selected.length===0||amount===''} onClick={sell}>{pending?'Проводим…':`Сдать ${totalWeight.toFixed(3)} кг`}</Button></div><p className="sm:col-span-2 lg:col-span-4 text-sm text-muted-foreground">Средняя цена: {totalWeight>0&&Number(amount)>=0?(Number(amount)/totalWeight).toFixed(2):'0,00'} UAH/кг</p></CardContent></Card>}
    <Card><CardHeader><CardTitle>Последние сдачи</CardTitle></CardHeader><CardContent className="space-y-2">{data.sales.map((sale:any)=><div key={sale.id} className="flex flex-wrap items-center justify-between gap-3 rounded-lg border p-3"><div><p className="font-medium">{sale.sale_date} · {Number(sale.total_weight_kg).toFixed(3)} кг · {Number(sale.amount_uah).toFixed(2)} UAH</p><p className="text-sm text-muted-foreground">{sale.buyer||'Покупатель не указан'} · {Number(sale.average_price_per_kg).toFixed(2)} UAH/кг · {sale.status==='cancelled'?'Отменена':'Проведена'}</p></div>{sale.status==='completed'&&data.canManageSales&&<Button variant="outline" disabled={pending} onClick={()=>cancel(sale.id)}>Отменить с причиной</Button>}</div>)}</CardContent></Card>
  </main>
}
