module.exports = {
  apps: [
    {
      name: 'nesting-api',
      script: 'dist/server.js',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      kill_timeout: 30000,
      max_memory_restart: '512M',
      out_file: '/dev/stdout',
      error_file: '/dev/stderr',
      merge_logs: true,
      time: true,
    },
    {
      name: 'step-worker',
      script: 'dist/workers/step-worker.js',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      restart_delay: 3000,
      kill_timeout: 30000,
      max_memory_restart: '1G',
      out_file: '/dev/stdout',
      error_file: '/dev/stderr',
      merge_logs: true,
      time: true,
    },
    {
      name: 'nesting-worker',
      script: 'dist/workers/nesting-worker.js',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      restart_delay: 3000,
      kill_timeout: 30000,
      max_memory_restart: '768M',
      out_file: '/dev/stdout',
      error_file: '/dev/stderr',
      merge_logs: true,
      time: true,
    },
  ],
};
