// Центральное хранилище всех URL-маршрутов приложения
// Никакого хардкода путей в компонентах — только из этого файла
export const ROUTES = {
  LOGIN:          '/login',
  PROFILE:        '/profile',
  DASHBOARD:      '/dashboard',
  ADMIN_USERS:    '/admin/users',
  ADMIN_USERS_NEW:'/admin/users/new',
  ADMIN_SUPPLIERS:'/admin/suppliers',
  ADMIN_SUPPLIERS_NEW:'/admin/suppliers/new',
  ADMIN_MATERIALS:'/admin/materials',
  ADMIN_SETTINGS:'/admin/settings',
  ADMIN_DEPARTMENTS:'/admin/settings/departments',
  ADMIN_ACCESS_SETTINGS:'/admin/settings/access',
  ADMIN_TELEGRAM_SETTINGS:'/admin/settings/telegram',
  ADMIN_COMPANY_SETTINGS:'/admin/settings/company',
  ADMIN_PRODUCTION_FACT_SETTINGS:'/admin/settings/production-fact',
  SALES_PLAN:          '/sales-plan',
  SALES_PLAN_NEW:      '/sales-plan/new',
  SALES_PLAN_PRICES:   '/sales-plan/prices',
  PRODUCTS:       '/products',
  PRODUCTS_NEW:   '/products/new',
  PRODUCT_PROJECTS:     '/product-projects',
  PRODUCT_PROJECTS_NEW: '/product-projects/new',
  CLIENTS:        '/clients',
  CONTRACTS:      '/contracts',
  FINANCE_CALENDAR:'/finance/calendar',
  TASKS:          '/tasks',
  MATERIAL_REQUESTS: '/material-requests',
  PRODUCTION:     '/production',
  GANTT:          '/production/gantt',
  PRODUCTION_FACT: '/production/fact',
  PRODUCTION_CONSUMABLE_REQUESTS: '/production/consumable-requests',
  PRODUCTION_CONSUMABLES: '/production/consumables',
  NESTING:        '/nesting',
  NESTING_CATALOG:'/nesting/catalog',
  NESTING_SETTINGS:'/nesting/settings',
  MEETINGS:       '/meetings',
  MEETINGS_NEW:   '/meetings/new',
  MEETINGS_AGENDA_POOL: '/meetings/agenda-pool',
  SUPPLY:         '/supply',
  SUPPLY_FINANCE: '/supply/finance',
  SUPPLY_MATERIAL_REQUESTS: '/supply/material-requests',
  SUPPLY_ORDERS:  '/supply/orders',
  SUPPLY_REQUEST: '/supply/request',
  SUPPLY_CONSUMABLE_REQUESTS: '/supply/production-requests',
  SUPPLY_TRANSPORT: '/supply/transport',
  INVENTORY:      '/inventory',
  INVENTORY_HISTORY: '/inventory/history',
  INVENTORY_RECEIVING: '/inventory/receiving',
  INVOICES:       '/invoices',
  NOTIFICATIONS:  '/notifications',
} as const

export type AppRoute = (typeof ROUTES)[keyof typeof ROUTES]
