ALTER TYPE "nesting"."ContourSource" ADD VALUE IF NOT EXISTS 'UNFOLDED_BREP';

ALTER TABLE "nesting"."Part"
  ADD COLUMN "bendCount" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "kFactor" DOUBLE PRECISION,
  ADD COLUMN "kFactorDefaulted" BOOLEAN NOT NULL DEFAULT false;
