import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import path from 'node:path'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const read = (relativePath: string) => readFileSync(path.join(root, relativePath), 'utf8')

const quickAdd = read('src/components/features/production/ProductionOutsourcingQuickAdd.tsx')
const outsourcingTab = read('src/components/features/outsourcing/OutsourcingTab.tsx')
const supplyWorkspace = read('src/components/features/supply/OutsourcingTransportPage.tsx')
const supplyRequests = read('src/components/features/supply/SupplyOutsourcingRequestsPage.tsx')
const supplyDrawingRoute = read('src/app/api/supply/outsourcing/[operationId]/drawings/[source]/[fileId]/route.ts')
const productionRequests = read('src/components/features/production/ProductionOutsourcingRequestsPage.tsx')
const productionPlanner = read('src/components/features/production/ProductionPlanner.tsx')
const productionWorkspace = read('src/components/features/production/ProductionWorkspace.tsx')
const outsourcingActions = read('src/lib/actions/outsourcing.ts')
const routes = read('src/lib/constants/routes.ts')
const resources = read('src/lib/permissions/resources.ts')
const productionPlanActions = read('src/lib/actions/production-plan.ts')
const migration = read('supabase/migrations/20260724175500_outsourcing_supply_terms_confirmation.sql')
const responsibilityMigration = read('supabase/migrations/20260725163031_add_outsourcing_responsibility_workflow.sql')
const databaseTypes = read('src/lib/types/database.ts')

assert.doesNotMatch(quickAdd, /Стоимость услуги/)
assert.doesNotMatch(outsourcingTab, /Field label="Стоимость услуги"/)
assert.match(quickAdd, /Другой тип работы/)
assert.match(quickAdd, /workTypeName: draft\.useCustomWorkType/)
assert.match(quickAdd, /Ответственный/)
assert.match(quickAdd, /Производство/)
assert.match(quickAdd, /Снабжение/)
assert.match(quickAdd, /Выберет снабжение после принятия заявки/)
assert.match(outsourcingTab, /Другой тип работы/)

assert.match(supplyWorkspace, /Согласование услуг аутсорсинга/)
assert.match(supplyWorkspace, /Стоимость услуги/)
assert.match(supplyWorkspace, /confirmOutsourcingServiceTerms/)
assert.match(supplyWorkspace, /Ожидает подтверждения/)
assert.match(supplyWorkspace, /Цена перевозки/)
assert.match(supplyRequests, /Запросы на аутсорсинг/)
assert.match(supplyRequests, /confirmOutsourcingServiceTerms/)
assert.match(supplyRequests, /takeOutsourcingSupplyRequest/)
assert.match(supplyRequests, /Взять в работу/)
assert.match(supplyRequests, /Цена аутсорсинга/)
assert.match(supplyRequests, /Дата запроса с/)
assert.match(supplyRequests, /Статус аутсорсинга/)
assert.match(supplyRequests, /Запрос создан:/)
assert.match(supplyRequests, /visibleAgreements/)
assert.match(supplyRequests, /Подробнее/)
assert.match(supplyRequests, /Сроки и примечание/)
assert.match(supplyRequests, /Продукция к отправке/)
assert.match(supplyRequests, /target="_blank"/)
assert.match(supplyRequests, /item\.drawing_number/)
assert.match(supplyRequests, /item\.weight/)
assert.match(supplyDrawingRoute, /requirePermission\('supply_transport', 'view'\)/)
assert.match(supplyDrawingRoute, /machine_outsourcing_operation_items/)
assert.match(supplyDrawingRoute, /belongsToRequest/)
assert.match(supplyDrawingRoute, /Content-Disposition/)
assert.match(productionRequests, /Желаемые даты отправителя/)
assert.match(productionRequests, /Начало у исполнителя/)
assert.match(productionRequests, /Конец у исполнителя/)
assert.match(productionPlanner, /OutsourcingStageCard/)
assert.match(productionPlanner, /Аутсорсинг/)
assert.match(productionWorkspace, /outsourcing:/)
assert.match(productionWorkspace, /display_label: operation\.work_type_name/)
assert.match(routes, /PRODUCTION_OUTSOURCING_REQUESTS/)
assert.match(routes, /SUPPLY_OUTSOURCING_REQUESTS/)
assert.match(resources, /ROUTES\.PRODUCTION_OUTSOURCING_REQUESTS/)
assert.match(resources, /ROUTES\.SUPPLY_OUTSOURCING_REQUESTS/)

const saveOperationSource = outsourcingActions.slice(
  outsourcingActions.indexOf('export async function saveOutsourcingOperation'),
  outsourcingActions.indexOf('export async function archiveOutsourcingOperation'),
)
assert.match(saveOperationSource, /resolveWorkTypeId/)
assert.doesNotMatch(saveOperationSource, /parsed\.serviceCostPlanned/)
assert.match(saveOperationSource, /supply_terms_confirmed_at = null/)

assert.match(outsourcingActions, /export async function confirmOutsourcingServiceTerms/)
assert.match(outsourcingActions, /export async function takeOutsourcingSupplyRequest/)
assert.match(outsourcingActions, /operation\.responsible === 'production'/)
assert.match(outsourcingActions, /Boolean\(operation\.supply_terms_confirmed_at\)/)
assert.match(outsourcingActions, /loadSupplyOutsourcingAgreements\(db, true\)/)
assert.match(outsourcingActions, /\.is\('supply_taken_at', null\)/)
assert.match(outsourcingActions, /service_cost_planned: parsed\.serviceCostPlanned/)
assert.match(outsourcingActions, /supply_terms_confirmed_at: now/)
assert.match(outsourcingActions, /syncConfirmedTransportForIncomingPlan/)
assert.match(outsourcingActions, /syncConfirmedTransportForSupplierOperation/)
assert.match(outsourcingActions, /reconcileConfirmedSupplierTransportNeeds\(db\)/)
assert.match(outsourcingActions, /created_at: operation\.created_at/)
assert.match(outsourcingActions, /\.eq\('task_type', 'outsourcing_transport'\)/)
assert.match(outsourcingActions, /\.in\('status', \['pending', 'in_progress'\]\)/)
assert.match(outsourcingActions, /Маршрут: \$\{routeLabel\}/)
assert.match(outsourcingActions, /Описание работы: \$\{operation\.note\}/)
assert.match(outsourcingActions, /Что забрать:/)
assert.match(outsourcingActions, /operation\.incoming_date_start/)
assert.match(outsourcingActions, /operation\.incoming_date_end/)
assert.match(outsourcingActions, /loadedOperations\.filter\(\(operation\) => operation\.executor_type === 'supplier'\)/)
assert.match(productionPlanActions, /supply_terms_confirmed_at: null/)
assert.match(migration, /ADD COLUMN IF NOT EXISTS supply_terms_confirmed_at/)
assert.match(migration, /ADD COLUMN IF NOT EXISTS supply_terms_confirmed_by/)
assert.match(responsibilityMigration, /outsourcing_responsible/)
assert.match(responsibilityMigration, /ADD COLUMN IF NOT EXISTS supply_taken_at/)
assert.match(responsibilityMigration, /responsible = 'supply'/)
assert.match(databaseTypes, /supply_terms_confirmed_at: string \| null/)
assert.match(databaseTypes, /outsourcing_responsible: 'production' \| 'supply'/)
assert.match(resources, /Надобности производства/)

console.log('outsourcing workflow checks: ok')
