export const BREADCRUMB_SEGMENT_LABELS: Record<string, string> = {
  dashboard: 'Дашборд',
  'sales-plan': 'План продаж',
  'product-projects': 'Проекты продукции',
  products: 'Продукция',
  mail: 'Почта',
  new: 'Создание',
  production: 'Производство',
  'cutting-area': 'Участок заготовки',
  request: 'Заявка на материалы',
  requests: 'Запросы',
  technologist: 'Технолог',
  gantt: 'Гант-график',
  consumables: 'Расходники',
  'consumable-requests': 'Заявки на расходники',
  supply: 'Снабжение',
  'production-requests': 'Надобности производства',
  transport: 'Транспорт',
  inventory: 'Склад',
  'metal-scrap': 'Металлолом',
  receiving: 'Приём материала',
  invoices: 'Инвойсы',
  reports: 'Отчёты',
  complex: 'Комплексные отчёты',
  contracts: 'Контракты',
  notifications: 'Уведомления',
  admin: 'Администрирование',
  settings: 'Настройки',
  'production-fact': 'Факт производства',
  access: 'Управление доступом',
  departments: 'Отделы и структура',
  users: 'Пользователи',
  materials: 'Материалы',
  suppliers: 'Поставщики',
  database: 'База данных',
  detail: 'Детали',
  complete: 'Завершение',
  correction: 'Исправление',
  all: 'Все компании',
  metal: 'Поставщики металла',
  outsourcing: 'Аутсорсинговые компании',
  'agenda-pool': 'Общая повестка',
  'business-scrap-reservations': 'Бронь делового остатка',
  calendar: 'Календарь',
  catalog: 'Каталог',
  clients: 'База клиентов',
  company: 'Компания',
  detailing: 'Деталировка',
  fact: 'Факт производства',
  factories: 'Заводы',
  'file-archive': 'Архив файлов',
  finance: 'Финансы',
  future: 'Будущая деталировка',
  history: 'История склада',
  login: 'Вход',
  'long-stock-layout': 'Раскладка хлыстов',
  'material-requests': 'Бронь склада',
  meetings: 'Совещания',
  nesting: 'Раскладка',
  orders: 'Заказы снабжения',
  payments: 'Оплаты',
  people: 'Планирование людей',
  prices: 'Цены',
  profile: 'Профиль',
  sales: 'Продажи',
  tasks: 'Задачи',
  telegram: 'Telegram',
  workers: 'Работники',
  parts: 'Детали',
  result: 'Результат',
}

export function breadcrumbLabelForSegment(segment: string) {
  const isId = segment.length > 20 && segment.includes('-')
  return isId ? 'Детали' : (BREADCRUMB_SEGMENT_LABELS[segment] || 'Раздел')
}
