ALTER TABLE nesting."Part"
  ADD COLUMN IF NOT EXISTS "bboxSizeX" DOUBLE PRECISION;

ALTER TABLE nesting."Part"
  ADD COLUMN IF NOT EXISTS "bboxSizeY" DOUBLE PRECISION;

ALTER TABLE nesting."Part"
  ADD COLUMN IF NOT EXISTS "bboxSizeZ" DOUBLE PRECISION;

ALTER TABLE nesting."Part"
  ADD COLUMN IF NOT EXISTS "meshVolume" DOUBLE PRECISION;

ALTER TABLE nesting."Part"
  ADD COLUMN IF NOT EXISTS "meshArea" DOUBLE PRECISION;

ALTER TABLE nesting."Part"
  ADD COLUMN IF NOT EXISTS "facesCount" INTEGER;
